### ISSUE TITLE
CTC error 

### ISSUE THREAD

**Issue by LeeBronOff23** [roatienza/deep-text-recognition-benchmark#34]
Hi. Appreciate  your contribution, but I have a problem：

CUDA_VISIBLE_DEVICES=4 python3 train.py --batch_ratio 1 --Transformation None --FeatureExtraction None --SequenceModeling None **--Prediction CTC** --Transformer --TransformerModel=vitstr_tiny_patch16_224 --imgH 224 --imgW 224 --manualSeed=27720
  
error:
Traceback (most recent call last):
  File "train.py", line 320, in <module>
    train(opt)
  File "train.py", line 175, in train
    preds = model(image, text)
UnboundLocalError: local variable 'text' referenced before assignment

**Comment by roatienza** [comment]
Sorry, the CTC prediction is not supported in vitstr
