### ISSUE TITLE
error in custom data

### ISSUE THREAD

**Issue by MahmoudElsayedMahmoud** [roatienza/deep-text-recognition-benchmark#45]
Filtering the images containing characters which are not in opt.character
Filtering the images whose label is longer than opt.batch_max_length
--------------------------------------------------------------------------------
dataset_root: ./datasets/lmbd3333333
opt.select_data: ['']
opt.batch_ratio: ['1']
--------------------------------------------------------------------------------
dataset_root:    ./datasets/lmbd3333333  dataset:
sub-directory:  /.       num samples: 6
num total samples of : 6 x 1.0 (total_data_usage_ratio) = 6
num samples of  per batch: 48 x 1.0 (batch_ratio) = 48
Traceback (most recent call last):
  File "D:\deep-text-recognition-benchmark\train.py", line 319, in <module>
    train(opt)
  File "D:\deep-text-recognition-benchmark\train.py", line 43, in train
    train_dataset = Batch_Balanced_Dataset(opt)
  File "D:\deep-text-recognition-benchmark\dataset.py", line 81, in __init__
    self.dataloader_iter_list.append(iter(_data_loader))
  File "C:\Users\user\miniconda3\envs\vitocr\lib\site-packages\torch\utils\data\dataloader.py", line 440, in __iter__
    return self._get_iterator()
  File "C:\Users\user\miniconda3\envs\vitocr\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\user\miniconda3\envs\vitocr\lib\site-packages\torch\utils\data\dataloader.py", line 1038, in __init__
    w.start()
  File "C:\Users\user\miniconda3\envs\vitocr\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\user\miniconda3\envs\vitocr\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\user\miniconda3\envs\vitocr\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Users\user\miniconda3\envs\vitocr\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\user\miniconda3\envs\vitocr\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'Environment' object

(vitocr) D:\deep-text-recognition-benchmark>
(vitocr) D:\deep-text-recognition-benchmark>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user\miniconda3\envs\vitocr\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\user\miniconda3\envs\vitocr\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by roatienza** [comment]
For non-latin, you may have to modify the character list and therefore the output layer

**Comment by MahmoudElsayedMahmoud** [comment]
can i train it in long sentences like that in arabic [":العنوان" "١٠٥ش" "بورسعيد" "-" "ميدان" "أبو" "الريش" "-" "بجوار" "محطة" "مترو" "السيدة" "زينب" "-" "امام" "حبايب" "السيدة"
] or it only for words ?
